changelog = """
## What's changed
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }} (`{{ commit.id | truncate(length=7, end="") }}`)
{% endfor %}
{% endfor %}
"""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^docs", group = "Documentation" },
  { message = "^refactor", group = "Maintenance" },
  { message = "^test", group = "Maintenance" },
  { message = "^ci", group = "Maintenance" },
  { message = "^chore", group = "Maintenance" },
  { message = ".*", group = "Other" }
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
